using Autodesk.DesignScript.Geometry;
using Autodesk.DesignScript.Runtime;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MatZeroTouch
{
    /// <summary>
    /// takes in a string, 
    /// converts the text shape into lines 
    /// and uses those lines to place walls
    /// </summary>
    public static class TextUtils
    {
        /// <summary>
        /// Converts a string into a list of segments
        /// </summary>
        /// <param name="text">String to convert</param>
        /// <param name="size">Text size</param>
        /// <returns></returns>
        [IsVisibleInDynamoLibrary(false)]
        public static IEnumerable<Line> TextToLines(string text, int size)
        {
            List<Line> lines = new List<Line>();

            //using System.Drawing for the conversion to font points
            using (Font font = new System.Drawing.Font("Arial", size, FontStyle.Regular))
            using (GraphicsPath gp = new GraphicsPath())
            using (StringFormat sf = new StringFormat())
            {
                sf.Alignment = StringAlignment.Center;
                sf.LineAlignment = StringAlignment.Center;

                gp.AddString(text, font.FontFamily, (int)font.Style, font.Size, new PointF(0, 0), sf);

                //convert font points to Dynamo points
                var points = gp.PathPoints.Select(p => Autodesk.DesignScript.Geometry.Point.ByCoordinates(p.X, -p.Y, 0)).ToList();
                var types = gp.PathTypes;

                Autodesk.DesignScript.Geometry.Point start = null;
                //create lines
                for (var i = 0; i < types.Count(); i++)
                {
                    //Types:
                    //0 start of a shape
                    //1 point in line
                    //3 point in curve
                    //129 partial line end
                    //131 partial curve end
                    //161 end of line
                    //163 end of curve
                    if (types[i] == 0)
                    {
                        start = points[i];
                    }
                    //some letters need to be closed other no
                    if (types[i] > 100)
                    {
                        if (!points[i].IsAlmostEqualTo(start))
                        {
                            lines.Add(Line.ByStartPointEndPoint(points[i], start));
                        }
                    }
                    else
                    {
                        lines.Add(Line.ByStartPointEndPoint(points[i], points[i + 1]));
                    }
                }
                //dispose points
                foreach (var point in points)
                {
                    point.Dispose();
                }
                return lines;
            }
        }
    }
}
